spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: mongo
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platfrom: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
        bootstrap-server: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          spring.json.type.mapping: paymentConfirmation:com.project.ecommerce.notification.PaymentNotificationRequest

server:
  port: 8060